config/routes.rb
Frab::Application.routes.draw do
  scope '(:locale)' do
    resource :session

    get '/conferences/new' => 'conferences#new', as: 'new_conference'
    post '/conferences' => 'conferences#create', as: 'create_conference'
    get '/conferences' => 'conferences#index', as: 'conference_index'
    delete '/conferences' => 'conferences#destroy'

    resources :people do
      resource :user
      member do
        put :attend
      end
    end

    scope path: '/:conference_acronym' do
      namespace :public do
        get '/schedule' => 'schedule#index', as: 'schedule_index'
        get '/schedule/style' => 'schedule#style', as: 'schedule_style'
        get '/schedule/:day' => 'schedule#day', as: 'schedule'
        get '/events' => 'schedule#events', as: 'events'
        get '/events/:id' => 'schedule#event', as: 'event'
        get '/speakers' => 'schedule#speakers', as: 'speakers'
        get '/speakers/:id' => 'schedule#speaker', as: 'speaker'

        resources :events do
          resource :feedback, controller: :feedback
        end
      end # namespace :public

      namespace :cfp do
        resource :session

        resource :user do
          resource :password
          resource :confirmation
        end

        resource :person do
          resource :availability
        end

        get '/events/:id/confirm/:token' => 'events#confirm', as: 'event_confirm_by_token'

        resources :events do
          member do
            put :withdraw
            put :confirm
          end
        end

        get '/open_soon' => 'welcome#open_soon', as: 'open_soon'
        get '/not_existing' => 'welcome#not_existing', as: 'not_existing'

        root to: 'people#show'
      end # namespace :cfp

      get '/recent_changes' => 'recent_changes#index', as: 'recent_changes'

      post '/schedule.pdf' => 'schedule#custom_pdf', as: 'schedule_custom_pdf', defaults: { format: :pdf }
      get '/schedule' => 'schedule#index', as: 'schedule'
      get '/schedule/update_track' => 'schedule#update_track', as: 'schedule_update_track'
      put '/schedule/update_event' => 'schedule#update_event', as: 'schedule_update_event'
      get '/schedule/new_pdf' => 'schedule#new_pdf', as: 'new_schedule_pdf'
      get '/schedule/html_exports' => 'schedule#html_exports'
      post '/schedule/create_static_export' => 'schedule#create_static_export'
      get '/schedule/download_static_export' => 'schedule#download_static_export'

      get '/statistics/events_by_state' => 'statistics#events_by_state', as: 'events_by_state_statistics'
      get '/statistics/language_breakdown' => 'statistics#language_breakdown', as: 'language_breakdown_statistics'
      get '/statistics/gender_breakdown' => 'statistics#gender_breakdown', as: 'gender_breakdown_statistics'

      resource :conference, except: [:new, :create] do
        get :edit_tracks
        get :edit_days
        get :edit_schedule
        get :edit_rooms
        get :edit_ticket_server
        get :edit_notifications
      end
      get '/conferences/default_notifications' => 'conferences#default_notifications', as: 'conferences_default_notifications'

      resource :call_for_participation

      resources :people do
        resource :user
        resource :availability, except: %i(create show)
        resources :expenses
        resources :transport_needs
        collection do
          get :all
          get :feedbacks
          get :speakers
        end
      end

      resources :events do
        collection do
          get :my
          get :ratings
          get :feedbacks
          get :start_review
          get :cards
          get :export_accepted
        end
        member do
          get :people
          get :edit_people
          get :ticket
          put :update_state
        end
        resource :event_rating
        resources :event_feedbacks
      end

      get '/reports' => 'reports#index', as: 'reports'
      get '/reports/on_people/:id' => 'reports#show_people', as: 'report_on_people'
      get '/reports/on_events/:id' => 'reports#show_events', as: 'report_on_events'
      get '/reports/on_statistics/:id' => 'reports#show_statistics', as: 'report_on_statistics'
      get "/reports/on_transport_needs/:id" => "reports#show_transport_needs", as: "report_on_transport_needs"

      resources :tickets do
        member do
          post :create
        end
      end

      resources :mail_templates do
        member do
          put :send_mail
        end
      end
    end # scope path: "/:conference_acronym"

    get '/:conference_acronym' => 'home#index', as: 'conference_home'
  end # scope "(:locale)" do

  root to: 'public/schedule#index'
end

app/models/event_feedback.rb
class EventFeedback < ActiveRecord::Base
  belongs_to :event, counter_cache: true

  after_save :update_average

  validates_presence_of :rating

  protected

  def update_average
    self.event.recalculate_average_feedback!
  end
end

app/controllers/event_feedbacks_controller.rb
class EventFeedbacksController < ApplicationController
  before_action :authenticate_user!
  before_action :not_submitter!

  def index
    authorize! :access, :event_feedback
    @event = Event.find(params[:event_id])
    @event_feedbacks = @event.event_feedbacks
  end
end

app/helpers/event_feedbacks_helper.rb
module EventFeedbacksHelper
end

app/views/event_feedbacks/index.html.haml
%section
  .page-header
    %h1 Event: #{@event.title}
  %ul.tabs
    %li= link_to "Event Details", @event
    %li= link_to "People", people_event_path(@event)
    %li= link_to "Ratings", event_event_rating_path(@event)
    %li.active= link_to "Feedback", event_event_feedbacks_path(@event)
  - if @event_feedbacks.all.empty?
    .row
      .span16
        .blank-slate
          %p
            There is no attendee feedback for this event yet.
          %p
            Enable attendee feedback in the conference
            settings and the web program schedule will include a
            form for your attendees to provide feedback. This
            feedback will appear here.
  - else
    .row
      .span16
        %p
          %b Average Feedback:
          %b= number_with_precision @event.average_feedback, precision: 2
          - if @event.event_feedbacks_count
            %br
            s<sub>N-1</sub> = #{@event.feedback_standard_deviation} n = #{@event.event_feedbacks_count}
        %h2 Comments
        %table.zebra-striped
          %thead
            %tr
              %th Rating
              %th Comment
          %tbody
            - @event_feedbacks.each do |feedback|
              - next if feedback.comment.blank?
              %tr
                %td
                  = raty_for("event_rating_#{feedback.id}", feedback.rating)
                %td= feedback.comment